name = "QInchworm"
uuid = "c1b6c5a0-2f71-4f50-a75d-692762eff855"
authors = ["Igor Krivenko <igor.s.krivenko@gmail.com>", "Hugo U. R. Strand <hugo.strand@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
