name: Build, test and deploy

on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ github.event_name }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'
          - '1.7'
          - '1.8'
          - '1.9'

    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1

      - name: Build documentation
        if: github.ref == 'refs/heads/main' && matrix.version == '1.9'
        run: |
             julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
             julia --project=docs/ docs/make.jl

      - name: Deploy documentation
        if: github.ref == 'refs/heads/main' && matrix.version == '1.9'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: docs/build
