name: Build, test and deploy

on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main

# Needed to allow julia-actions/cache to delete old caches
permissions:
  actions: write
  contents: write

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ github.event_name }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'
          - '1.7'
          - '1.8'
          - '1.9'
          - '1.10'

    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-docdeploy@v1
        if: github.ref == 'refs/heads/main' && matrix.version == '1.10'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
